version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-mysql.properties
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - mysql:mysql
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'conductor'
      MYSQL_USER: 'uconductor'
      MYSQL_PASSWORD: 'pconductor'
      MYSQL_ROOT_PASSWORD: 'rconductor'
    networks:
      - internal
    ports:
      - '3306:3306'
    volumes:
      - '/docker-volumes/orchestrator/mysql:/var/lib/mysql'
    healthcheck:
      test: "/usr/bin/mysql --user=uconductor --password=pconductor --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"


  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - '/docker-volumes/orchestrator/mongo/:/data/db'
    networks:
      - internal
    logging:
      driver: none

networks:
  internal:
